# Generated by Django 3.1.2 on 2020-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0002_auto_20201010_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='№'),
        ),
    ]
